name: GitHub Pageséƒ¨ç½²
run-name: ${{ github.actor }} æ­£åœ¨éƒ¨ç½²GitHub Pages ğŸš€
on: 
  # Runs on pushes targeting the default branch
  push:
    branches: master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    name: æ„å»º
    permissions:
      contents: write
    steps:
      - name: ç­¾å‡ºä»£ç 
        uses: actions/checkout@v3

      - name: å®‰è£…nodejs V20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: å®‰è£…ä¾èµ–+æ‰“åŒ…
        run: |
          npm install
          npm run build

      - name: ä¸Šä¼ æ‰“åŒ…ç»“æœ
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: éƒ¨ç½²
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

